# CI/CD

stages:
  - build
  - test

compile_statics:
  image: node
  stage: build
  before_script:
    - npm install -g webpack @vue/cli @vue/cli-service-global
    - cd vue/builder && npm install
  script:
    - cd vue/builder/src && vue build
  artifacts:
    paths:
      - vue/builder/src/dist

run_app:
  image: python
  stage: test
  dependencies:
    - compile_statics
  before_script:
   - pip install django
   - mv vue/builder/src/dist django/application/static
  script:
    - cd django/application && ls static && python manage.py runserver &
    - kill %1
  artifacts:
    paths:
      - django/application

