version: "3.7"
services:
  backend:
    build: ./backend
    image: develin/backend:prod
    ports:
      - 8000:8000
  frontend:
    build: ./frontend
    image: develin/frontend:prod
    ports:
      - 8080:8080

