version: "3.7"
services:

  backend:
    #build: ./backend
    image: bluebrown/django-vue/backend:prod
    restart: always
    ports:
      - 8000:8000

  frontend:
    #build: ./frontend
    image: bluebrown/django-vue/frontend:prod
    restart: always
    ports:
      - 8080:8080

  database:
    image: postgres
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

