version: "3.7"
services:
  backend:
    build: ./django
    image: develin/backend
    ports:
      - 8000:8000
  frontend:
    build: ./gin-vue
    image: develin/frontend
    ports:
      - 8080:8080

